---
# tasks file for role-vector
- name: SYSTEM | Update repo for CentOS
  ansible.builtin.include_tasks: update_repo.yml
  when: ansible_pkg_mgr == "dnf"
  

- name: Get vector distrib
  block:
    - name: Centos Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "./vector-{{ vector_version }}.rpm"
        mode: "0644"
      notify: Start vector
      when: ansible_pkg_mgr == "dnf"
    - name: debian Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
        dest: "./vector_{{ vector_version }}-1_amd64.deb"
        mode: "0644"
      when: ansible_os_family == "Debian"
      notify: Start vector



- name: Install vector packages
  block:
    - name: Centos install vector packages
      ansible.builtin.dnf:
        name:
          - vector-{{ vector_version }}.rpm
        state: present
        disable_gpg_check: true
      when: ansible_pkg_mgr == "dnf"
    - name: Debian install vector packages
      ansible.builtin.apt:
        deb: "./vector_{{ vector_version }}-1_amd64.deb"
        state: present
      when: ansible_os_family == "Debian"
    
- name: Configure Vector
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: "0644"


- name: vector config
  ansible.builtin.template:
    src: "templates/vector.yml.j2"
    dest: "{{ vector_config_dir }}/vector.yml"
    mode: "0644"

- name: Flush handlers to restart vector
  ansible.builtin.meta: flush_handlers