---
# tasks file for role-vector
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}.rpm"
    mode: "0644"
  notify: Start vector
- name: Install vector packages
  ansible.builtin.yum:
    name:
      - vector-{{ vector_version }}.rpm
- name: Flush handlers to restart vector
  ansible.builtin.meta: flush_handlers
- name: Configure Vector
  ansible.builtin.file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: "0644"
- name: Template config
  ansible.builtin.template:
    src: "template/vector.yml.j2"
    dest: "{{ vector_config_dir }}/vector.yml"
    mode: "0644"