---
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
platforms:
  - name: podman
    image: aragast/netology
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy